[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

# Optional settings to improve the build process
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[context.branch-deploy]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"